import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'getting-started/setting-up',
        },
        {
          type: 'doc',
          id: 'getting-started/configuring',
        },
        {
          type: 'doc',
          id: 'getting-started/install',
        },
        {
          type: 'doc',
          id: 'getting-started/wrapping-up',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one OS',
      items: [
        {
          type: 'doc',
          id: 'pi-one-os/os',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one linux kernel',
      items: [
        {
          type: 'doc',
          id: 'pi-one-linux-kernel/yocto',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one uboot',
      items: [
        {
          type: 'doc',
          id: 'pi-one-uboot/uboot',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one hardware',
      items: [
        {
          type: 'doc',
          id: 'pi-one-hardware/hardware',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one camera',
      items: [
        {
          type: 'doc',
          id: 'pi-one-camera/camera',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'PI one display',
      items: [
        {
          type: 'doc',
          id: 'pi-one-display/display',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Datasheets',
      items: [
        {
          type: 'doc',
          id: 'datasheets/datasheets',
        },
      ],
    },
  ],
   
};

export default sidebars;
