import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      collapsed: true,
      label: 'K1',
      items: [
        {
          type: 'category',
          collapsed: true,
          label: 'Getting Started',
          items: [
            {
              type: 'doc',
              label: 'Getting Started',
              id: 'k1/getting-started/preparation',
            },
            {
              type: 'doc',
              label: 'Downloading and Installing the OS',
              id: 'k1/getting-started/install',
            },
            {
              type: 'doc',
              label: 'Starting and Configuring K1',
              id: 'k1/getting-started/configuring',
            }

          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Bianbu OS',
          items: [
            {
              type: 'category',
              collapsed: true,
              label: 'Desktop',
              items: [
                {
                  type: 'doc',
                  label: 'Introduction to Bianbu OS',
                  id: 'k1/k1-os/desktop/os-intro',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-os/desktop/bianbu_desktop_2.0',
                },
                {
                  type: 'doc',
                  label: 'Networking and Upgrading',
                  id: 'k1/k1-os/desktop/installation-and-upgrade',
                },
                {
                  type: 'doc',
                  label: 'Package Management',
                  id: 'k1/k1-os/desktop/package-management',
                },
              ]
            },
            {
              type: 'category',
              collapsed: true,
              label: 'NAS',
              items: [
                {
                  type: 'doc',
                  id: 'k1/k1-os/nas/README',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-os/nas/login',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-os/nas/base_setup',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-os/nas/shared_services_setup',
                },
                {
                  type: 'category',
                  collapsed: true,
                  label: 'Docker Service',
                  items: [
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/applications',
                    },
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/docker-compose',
                    },
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/nextcloud',
                    },
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/kodbox',
                    },
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/frigate',
                    },
                    {
                      type: 'doc',
                      id: 'k1/k1-os/nas/docker_setup/immich',
                    },
                  ]},
              ]
            },
            {
              type: 'category',
              collapsed: true,
              label: 'Development Guide',
              items: [{
                type: 'doc',
                label: 'ROS2 Installation',
                id: 'k1/news/ros2',
              },
              {
                type: 'doc',
                label: 'Docker ',
                id: 'k1/k1-os/software/docker',
              },
              {
                type: 'doc',
                label: 'JavaScript Use Guide',
                id: 'k1/k1-os/software/electron',
              },
              {
                type: 'doc',
                label: 'Python Use Guide',
                id: 'k1/k1-os/software/python',
              },
              {
                type: 'doc',
                label: 'QT Use Guide',
                id: 'k1/k1-os/software/qt',
              },
              {
                type: 'doc',
                label: 'Remote Development',
                id: 'k1/k1-os/software/remote_development',
              },
              {
                type: 'doc',
                label: 'Perf Usage Note',
                id: 'k1/k1-os/software/perf',
              },]
            },
            {
              type: 'category',
              collapsed: true,
              label: 'System Integration',
              items: [{
                type: 'doc',
                label: 'Bianbu 2.0 ROOTFS Creation Guide',
                id: 'k1/k1-os/rootfs/bianbu_2.0_rootfs_create',
              },
            ]
            },
          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'System Development Guide',
          items: [
            {
              type: 'category',
              collapsed: true,
              label: 'Bianbu Linux',
              items: [
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/bianbu-linux-intro',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/build-bit-os',
                },
                {
                  type: 'doc',
                  label: 'U-Boot Development',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/boot',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/kernel-build',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/device-manage',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/bianbu-linux/solution-manage',
                },
              ]
            }, 
            {
              type: 'category',
              collapsed: true,
              label: 'OpenWrt',
              items: [
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/openwrt/openwrt_intro',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/openwrt/openwrt_quickstart',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/openwrt/openwrt_device_management',
                },
                {
                  type: 'doc',
                  id: 'k1/k1-bianbu-linux/openwrt/openwrt_solution_management',
                },
                
              ]
            },   

            

          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Hardware Development Guide',
          items: [
            {
              type: 'doc',
              label: 'K1 Hardware Specifications',
              id: 'k1/k1-hardware/hardware-brief',
            },
            {
              type: 'doc',
              label: 'K1 Application Processor',
              id: 'k1/k1-hardware/processor-brief',
            },
            {
              type: 'doc',
              label: 'K1 GPIO Expansion Interface',
              id: 'k1/k1-hardware/GPIO-and-40-pin-header',
            },
            {
              type: 'doc',
              label: 'K1 M.2 Interface',
              id: 'k1/k1-hardware/m2-interface',
            },
            {
              type: 'doc',
              label: 'K1 Camera Interface',
              id: 'k1/k1-hardware/camera-interface',
            },
            {
              type: 'doc',
              label: 'K1 Display Interface',
              id: 'k1/k1-hardware/display-interface',
            },

            {
              type: 'doc',
              label: 'K1 Audio Interface',
              id: 'k1/k1-hardware/audio-hardware-introduction',
            },
            // {
            //   type: 'doc',
            //   label: 'K1 Power Sequence',
            //   id: 'k1/k1-hardware/power-sequence',
            // },
            {
              type: 'doc',
              label: 'Download of K1 Hardware Documentation',
              id: 'k1/k1-hardware/hardware-file-download',
            },


          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Software Development Guide',
          items: [
            {
              type: 'doc',
              label: 'K1 PINCTRL',
              id: 'k1/k1-software/PINCTRL',
            },
            {
              type: 'doc',
              label: 'K1 GPIO',
              id: 'k1/k1-software/GPIO',
            },
            {
              type: 'doc',
              label: 'K1 PWM',
              id: 'k1/k1-software/PWM',
            },
            {
              type: 'doc',
              label: 'K1 IR-RX',
              id: 'k1/k1-software/IR-RX',
            },
            {
              type: 'doc',
              label: 'K1 UART',
              id: 'k1/k1-software/UART',
            },
            {
              type: 'doc',
              label: 'K1 I2C',
              id: 'k1/k1-software/I2C',
            },
            {
              type: 'doc',
              label: 'K1 QSPI',
              id: 'k1/k1-software/QSPI',
            },
            {
              type: 'doc',
              label: 'K1 SDHC',
              id: 'k1/k1-software/SDHC',
            },
            {
              type: 'doc',
              label: 'K1 GMAC',
              id: 'k1/k1-software/gmac',
            },
            {
              type: 'doc',
              label: 'K1 USB',
              id: 'k1/k1-software/USB',
            },
            {
              type: 'doc',
              label: 'K1 PCIE',
              id: 'k1/k1-software/PCIe',
            },
            {
              type: 'doc',
              label: 'K1 Camera',
              id: 'k1/k1-software/Camera',
            },
            {
              type: 'doc',
              label: 'K1 DSI',
              id: 'k1/k1-software/DSI',
            },
            {
              type: 'doc',
              label: 'K1 HDMI',
              id: 'k1/k1-software/HDMI',
            },
            {
              type: 'doc',
              label: 'K1 PMIC',
              id: 'k1/k1-software/PMIC',
            },
          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Machine Learning',
          items: [
            {
              type: 'doc',
              label: 'Introduction to Computing Architecture',
              id: 'k1/k1-ml/ai-arch',
            },
            {
              type: 'doc',
              label: 'Overview of Tools',
              id: 'k1/k1-ml/tools-overview',
            },
            {
              type: 'doc',
              label: 'Quick Start',
              id: 'k1/k1-ml/ai-quick-start',
            },
            {
              type: 'doc',
              label: 'Model Translation',
              id: 'k1/k1-ml/model-translate',
            },
            {
              type: 'doc',
              label: 'Model Optimization',
              id: 'k1/k1-ml/model-optimization',
            },
            {
              type: 'doc',
              label: 'Model Simulation and Testing',
              id: 'k1/k1-ml/model-simulation-testing',
            },
            {
              type: 'doc',
              label: 'Model Deployment',
              id: 'k1/k1-ml/model-deploy',
            },
            {
              type: 'doc',
              id: 'k1/k1-ml/llm-deploy',
            },

          ],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Data Manual',
          items: [
            {
              type: 'doc',
              id: 'k1/datasheets/datasheets',
            },
          ],
        },

      ],
    }
  ],

};

export default sidebars;
